Repository Blind-Dating/Blind-Dating-FE, pull requests merged in 2023-09, with the labels that each got.

#133 [FE] DIscover Page 로직 분리 및 데이터 없을 시 보이는 컴포넌트 생성
  client/src/assets/icons/noUserList.svg
  client/src/components/discover/DiscoverUser.tsx
  client/src/components/discover/NoUserListData.tsx
  client/src/components/ui/LoadingSpinner.tsx
  client/src/pages/DiscoverPage.tsx
Labels: feat, refactor

#135 [FE] 채팅 소켓 연결 에러 수정
  client/src/hooks/useHandleChat.ts
  client/src/hooks/useHandleChatList.ts
Labels: chore

#137 [FE] 프로필 페이지 정보 state 수정
  client/src/components/profile/detail/DetailFields.tsx
  client/src/pages/ProfilePage.tsx
Labels: chore

#139 [FE] SignUp Page 에러 해결
  client/src/components/sign-up/introduction/IntroductionForm.tsx
  client/src/components/sign-up/your-interest/YourInterestForm.tsx
Labels: fix

#141 [FE] SignUp Page 성격 테스트 & 관심사 폼 기능 수정
  client/src/components/sign-up/personality-test/PersonalityTestForm.tsx
  client/src/components/sign-up/personality-test/QuestionField.tsx
  client/src/components/sign-up/your-interest/InterestField.tsx
  client/src/components/sign-up/your-interest/YourInterestForm.tsx
  client/src/index.css
  client/src/recoil/sign-up/atoms.ts
  client/src/recoil/sign-up/selectors.ts
Labels: feat, style

#143 [FE] Footer 기능 활성화
  client/src/assets/icons/cards.svg
  client/src/assets/icons/likes.svg
  client/src/assets/icons/messages.svg
  client/src/assets/icons/user.svg
  client/src/components/layout/Footer.tsx
  client/src/components/layout/Layout.tsx
  client/src/components/layout/Navbar.tsx
  client/src/components/layout/footer/Footer.tsx
  client/src/components/layout/footer/FooterBtn.tsx
  client/src/pages/ChatListPage.tsx
  client/src/pages/DiscoverPage.tsx
  client/src/pages/ProfilePage.tsx
  client/src/routes/ProtectedRouter.tsx
Labels: feat, refactor

#145 [FE] Discover Page 유저 추천 카드 기능 수정
  client/index.html
  client/src/components/discover/DetailField.tsx
  client/src/components/discover/RecommendedUserCard.tsx
Labels: feat

#147 [Test] test socket url 반영
  client/src/hooks/useHandleChatList.ts
Labels: chore

#149 [Test] modify socket url
  client/src/hooks/useHandleChatList.ts
Labels: chore

#153 [FE] 채팅창 나가기 수정
  client/src/components/chat/ChatUser.tsx
  client/src/pages/ChatPage.tsx
Labels: chore

#155 [FE] 유저 정보 account id 추가
  client/src/components/profile/UserInfo.tsx
  client/src/hooks/api/usePostLogin.ts
  client/src/hooks/useVerifyToken.ts
  client/src/pages/ProfilePage.tsx
  client/src/recoil/user/atoms.ts
Labels: chore

#157 [FE] 프로필 페이지 모달 닫기
  client/src/assets/icons/close.svg
  client/src/components/profile/detail/DetailFields.tsx
  client/src/components/profile/detail/detail-info-tags/TagsModal.tsx
Labels: chore

#158 [FE] 레이아웃 공통 header 생성
  client/index.html
  client/src/assets/icons/menu_icon.svg
  client/src/components/discover/DiscoverUser.tsx
  client/src/components/discover/LikeDisLikeBox.tsx
  client/src/components/layout/Header.tsx
  client/src/components/layout/Layout.tsx
  client/src/components/layout/Navbar.tsx
  client/src/components/layout/NoHeaderFooterLayout.tsx
  client/src/components/layout/auth-layout/AuthLayout.tsx
  client/src/components/layout/auth-layout/Header.tsx
  client/src/components/layout/footer/Footer.tsx
  client/src/components/layout/footer/FooterBtn.tsx
  client/src/components/sign-up/introduction/IntroductionForm.tsx
  client/src/components/sign-up/personality-test/PersonalityTestForm.tsx
  client/src/components/sign-up/profile-details/ProfileDetailsForm.tsx
  client/src/components/sign-up/profile/ProfileForm.tsx
  client/src/components/sign-up/your-interest/YourInterestForm.tsx
  client/src/pages/ChatListPage.tsx
  client/src/pages/ChatPage.tsx
  client/src/pages/DiscoverPage.tsx
  client/src/pages/LoginPage.tsx
  client/src/pages/ProfilePage.tsx
  client/src/pages/ReceivedLikesPage.tsx
  client/src/pages/SignUpPage.tsx
  client/src/routes/router.tsx
  client/tailwind.config.js
Labels: feat, style

#161 [FE] 프로필 페이지 수정
  client/src/components/chat-list/ChatItem.tsx
  client/src/components/chat/ChatForm.tsx
  client/src/components/chat/ChatUser.tsx
  client/src/components/layout/Header.tsx
  client/src/components/profile/UserInfo.tsx
  client/src/components/profile/UserInfoEditBtn.tsx
  client/src/components/profile/detail/DetailFields.tsx
  client/src/components/profile/detail/Introduction.tsx
  client/src/components/profile/detail/detail-info-tags/TagsModal.tsx
  client/src/components/profile/logout/LogoutBtn.tsx
  client/src/pages/ProfilePage.tsx
Labels: chore

#164 [FE] Layout NavBar 기능 & CSS
  client/src/assets/icons/close_icon.svg
  client/src/assets/icons/menu_icon.svg
  client/src/components/layout/Layout.tsx
  client/src/components/layout/NavBar.tsx
  client/src/components/sign-up/profile-details/ProfileDetailsForm.tsx
  client/src/components/sign-up/profile/ProfileForm.tsx
  client/src/hooks/api/usePostLogout.ts
  client/src/index.css
Labels: feat, style

#166 [FE] 채팅 페이지 수정
  client/src/components/chat-list/ChatSettingBtn.tsx
  client/src/components/chat/Chat.tsx
  client/src/components/chat/ChatUser.tsx
  client/src/components/profile/Profile.tsx
  client/src/components/profile/UserInfo.tsx
  client/src/pages/ChatPage.tsx
  client/src/pages/ProfilePage.tsx
Labels: chore

#168 [Chore] fix 파일 수정 오류
  client/src/hooks/api/usePostEditProfile.ts
Labels: chore

#170 [FE] 각종 미흡한 CSS 수정
  client/src/assets/icons/Arrow_Right.svg
  client/src/assets/icons/apple.png
  client/src/assets/icons/close_icon.svg
  client/src/assets/icons/facebook.png
  client/src/assets/icons/google.png
  client/src/assets/icons/menu_icon.svg
  client/src/components/chat-list/ChatList.tsx
  client/src/components/chat-list/NoChatListData.tsx
  client/src/components/discover/DiscoverUser.tsx
  client/src/components/discover/NoUserListData.tsx
  client/src/components/discover/RecommendedUserCard.tsx
  client/src/components/layout/Header.tsx
  client/src/components/layout/auth-layout/AuthLayout.tsx
  client/src/components/layout/footer/Footer.tsx
  client/src/components/sign-up/introduction/IntroductionForm.tsx
  client/src/components/sign-up/personality-test/PersonalityTestForm.tsx
  client/src/components/sign-up/profile-details/MoreModal.tsx
  client/src/components/sign-up/profile-details/ProfileDetailsForm.tsx
  client/src/components/sign-up/profile/ProfileForm.tsx
  client/src/components/sign-up/your-interest/YourInterestForm.tsx
  client/src/index.css
  client/src/pages/DiscoverPage.tsx
  client/src/pages/LoginPage.tsx
Labels: style, refactor

#171 [FE] 접근성 향상
  client/src/components/chat-list/ChatSettingBtn.tsx
  client/src/components/chat-list/DeleteChatBtn.tsx
  client/src/components/chat/ChatForm.tsx
  client/src/components/chat/ChatUser.tsx
  client/src/components/layout/NavBar.tsx
  client/src/components/layout/footer/Footer.tsx
  client/src/components/layout/footer/FooterBtn.tsx
  client/src/components/profile/detail/detail-info-tags/TagsModal.tsx
  client/src/pages/ChatPage.tsx
Labels: chore
