Repository Blind-Dating/Blind-Dating-FE, pull requests merged in 2023-08, with the labels that each got.

#16 폰트 적용
  client/package-lock.json
  client/package.json
  client/src/main.tsx
  client/src/pages/HomePage.tsx
  client/tailwind.config.js
Labels: feat

#19 로그인 페이지 마크업 & 로그인 기능 구현
  client/src/axios/index.ts
  client/src/components/layout/NoHeaderFooterLayout.tsx
  client/src/components/login/LoginForm.tsx
  client/src/components/sign-up/ProfileDetailsForm.tsx
  client/src/components/sign-up/ProfileForm.tsx
  client/src/hooks/api/useGetIdCheck.ts
  client/src/hooks/api/usePostCheckName.ts
  client/src/hooks/api/usePostLogin.ts
  client/src/hooks/api/usePostSignUpData.ts
  client/src/hooks/useHookForm.ts
  client/src/hooks/useModal.ts
  client/src/index.css
  client/src/pages/LoginPage.tsx
  client/src/pages/SignUpPage.tsx
  client/src/routes/router.tsx
  client/tailwind.config.js
Labels: feat, style

#21 [Fix] axios path 에러
  client/src/apis/axiosClient.ts
  client/src/hooks/api/useGetIdCheck.ts
  client/src/hooks/api/usePostCheckName.ts
  client/src/hooks/api/usePostLogin.ts
  client/src/hooks/api/usePostSignUpData.ts
Labels: fix

#22 [Feat] 로그인 기능 구현
  client/src/components/login/LoginForm.tsx
  client/src/hooks/api/usePostLogin.ts
  client/src/pages/DateDiscoverPage.tsx
  client/src/routes/router.tsx
Labels: feat

#26 [FE] 메세지 페이지 마크업
  client/src/components/messages/MessageItem.tsx
  client/src/components/messages/MessageList.tsx
  client/src/pages/MessagesPage.tsx
  client/src/routes/router.tsx
Labels: style

#27 [FE] 회원가입 profile 페이지 마크업
  client/package-lock.json
  client/package.json
  client/src/components/layout/NoHeaderFooterLayout.tsx
  client/src/components/sign-up/ProfileForm.tsx
  client/src/components/ui/InputField.tsx
  client/src/index.css
  client/svg.d.ts
  client/tailwind.config.js
  client/tsconfig.json
  client/vite.config.ts
Labels: style

#29 [FE] 회원가입 profile 페이지 기능
  client/package-lock.json
  client/package.json
  client/public/icons/dot.svg
  client/src/components/login/LoginForm.tsx
  client/src/components/sign-up/ProfileForm.tsx
  client/src/hooks/api/useGetIdCheck.ts
  client/src/hooks/api/usePostCheckId.ts
  client/src/hooks/api/usePostCheckName.ts
  client/src/hooks/api/usePostCheckNickname.ts
  client/src/index.css
  client/src/pages/LoginPage.tsx
Labels: feat

#30 [FE] 메세지 페이지 nav, footer 마크업
  client/public/icons/cards.svg
  client/public/icons/likes.svg
  client/public/icons/messages.svg
  client/public/icons/setting-config.svg
  client/public/icons/user.svg
  client/src/components/layout/Footer.tsx
  client/src/components/layout/Layout.tsx
  client/src/components/layout/Navbar.tsx
  client/src/components/messages/MessageItem.tsx
  client/src/components/messages/MessageList.tsx
  client/src/pages/MessagesPage.tsx
Labels: style

#34 [FE] 회원가입 Profile Details 페이지 마크업
  client/src/components/sign-up/ProfileDetailsForm.tsx
  client/src/index.css
Labels: style
